version: '2'
services:
  dropbox:
    image: $DROPBOX_IMAGE
    labels:
      io.rancher.scheduler.affinity:host_label: dropbox=true
    environment:
      ENABLE_DROPBOX_IGNORE: false
      DROPBOX_UID: 1000
      DROPBOX_GID: 1000
    volumes:
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime
    - $DROPBOX_PATH:/opt/dropbox/Dropbox
    - $DROPBOX_SETTINGS_PATH:/opt/dropbox/.dropbox
    network_mode: host
