name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          tag_with_ref: true
          tag_with_sha: true
          tags: github-ci

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: chipsu/rancher-deploy-action@v1
        with:
          url: ${{ secrets.RANCHER_URL }}
          access_key: ${{ secrets.RANCHER_ACCESS_KEY }}
          secret_key: ${{ secrets.RANCHER_SECRET_KEY }}
          stack: ${{ secrets.RANCHER_STACK }}
        env:
          DROPBOX_IMAGE: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}
          DROPBOX_PATH: ${{ secrets.DROPBOX_PATH }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}
          DROPBOX_SETTINGS_PATH: ${{ secrets.DROPBOX_SETTINGS_PATH }}
